### ISSUE TITLE
Deploying to aws zips the entire project directory rather than the required modules/directories (or an artifact generated by the build command)

### ISSUE THREAD

**Issue by terencemackie** [jovotech/jovo-cli#10]
When executing `jovo deploy` with a target of lambda (or all), then the zip file that is uploaded to the aws lambda includes all files in the directory (including any artifacts created in the build (and deploy) process for alexa or google assistant). 

Ideally, the build command `jovo build` would support the "building" of lambda zip file artifacts. This could be the bare basic of zipping the files required for the lambda (and it's dependencies). The deploy command `jovo deploy` would then deploy this zip file to the lambda.

**Comment by terencemackie** [comment]
Awesome, thanks @jankoenig.

**Comment by aswetlow** [comment]
Added in 1.0.11

Usage:
jovo deploy --target lambda --src <pathToSrcFiles>

Make sure node_modules is in the same folder.

**Comment by fgnass** [comment]
This is what we do right now:

```
#!/bin/bash

set -e
mkdir -p platforms/lambda
cp -r app index.js package.json platforms/lambda

# exclude tests, snapshots and fixtures:
rm -rf platforms/lambda/app/__*

cd platforms/lambda
npm i --production

cd ../../
jovo deploy -t lambda --src platforms/lambda
```

Having something like this built into jovo-cli would probably be useful everyone using lambda functions. What do you think, should I open a new issue?

**Comment by jankoenig** [comment]
Hi @fgnass, this is an interesting workflow. Would love to discuss it in an issue. Thanks!
