### ISSUE TITLE
config.js not found when deployed to lambda

### ISSUE THREAD

**Issue by stuart-clark-45** [jovotech/jovo-cli#101]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

config.js/config.ts used when deployed to lambda

## Current Behavior
File is not being found when deployed to lambda however it does work fine locally 

I have used the following to hack my way round it for now
```
tsc ./src/config.ts && cp ./src/config.js bundle/config.js
```

### Error log
```
 WARN: Expected path: /var/task/config.js
```

## Your Environment

* Jovo CLI version used: 2.2.14
* Operating System: AWS Lambda

**Comment by aswetlow** [comment]
Hey @stuart-clark-45 

Do have an idea how to reproduce it?

What I tried:

```
jovo new <project> --language typescript
cd <project>
jovo build
jovo deploy
```
The bundle.zip, which is uploaded to Lambda, does have the `config.js` file.

**Comment by stuart-clark-45** [comment]
@aswetlow I would expect that to do the trick. I do have the `config.js` file in the bundle however it is in `src/config.js` rather than `./`.

If you check the cloud watch logs do you get  `WARN: Expected path: /var/task/config.js`?

**Comment by rubenaeg** [comment]
Closing this for now due to inactivity. If the issue still persists, feel free to reopen.
