### ISSUE TITLE
404 on https://www.jovo.tech/repo/sample-apps/

### ISSUE THREAD

**Issue by 32teeth** [jovotech/jovo-cli#102]
## I'm submitting a...

- [*] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

# 404
https://www.jovo.tech/repo/sample-apps/

**Comment by rubenaeg** [comment]
If you want to have a look at our templates, you can find them [here](https://www.jovo.tech/templates).
