### ISSUE TITLE
jovo deploy should allow override of default ASK skill name

### ISSUE THREAD

**Issue by asarazan** [jovotech/jovo-cli#103]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
When auto-creating a new skill using the ASK sdk, it would be great if `jovo deploy` defaulted to the `name` field of package.json, or had an override option in project.js

## Current Behavior
It seems that `deploy` currently grabs the name of the enclosing directory when auto-creating an Alexa skill. Unfortunately if you have a large, multi-package repo, the actual directory might be named something generic like `app` or `skill`.

## Your Environment

* Jovo CLI Version: 2.2.14
* Operating System: OS X

**Comment by jankoenig** [comment]
Hi @asarazan, you can override it by using the `skill.json Overrides` in the Jovo `project.js`. Take a look here: https://www.jovo.tech/docs/project-js#skilljson-overrides

Don't forget to do a `jovo  build` before the `jovo deploy`, then it should work :)

**Comment by jankoenig** [comment]
Maybe this video is helpful as well: https://www.youtube.com/watch?v=1fOsfy7crqU

It introduces the Jovo staging feature

**Comment by asarazan** [comment]
Ah this makes sense. I hadn't used the skill manifest overrides yet. Thanks!

**Comment by jankoenig** [comment]
Great. Closing this 👍
