### ISSUE TITLE
Forever or Service (Init.d) BUG

### ISSUE THREAD

**Issue by marab2** [jovotech/jovo-cli#104]
I've created a init.d service script to keep jovo running, but for unknown reason, the script is working fine with the Jovo Debugger Webhook but it doesn't work with Google Dialog flow, But when I do the manual start for jovo with jovo run, everything works perfect, the Jovo Debbuger Webhook and the Google Dialog.

Here is a copy of my init.d service script
Attached: https://pastebin.com/Q8ADJJPc

To conclude, I want anything that keeps Jovo running while my terminal is closed, I tried nohup, I tried forever, but all is leading into the same issue, it works with the online webhook but not Google Dialog.

**Comment by marab2** [comment]
I figured out a way to run jovo run --watch, but you have to keep one terminal open to keep it running.

**Comment by aswetlow** [comment]
Just in case. Please do not use `jovo run` in production :)

**Comment by marab2** [comment]
I solve it out by running first
screen
then
jovo run --watch
close the terminal and still running...

**Comment by aswetlow** [comment]
Is this your `in development` setup?

**Comment by rubenaeg** [comment]
Closing this for now as the original issue has been resolved.
