### ISSUE TITLE
Allow to chain jovo get and jovo build --reverse

### ISSUE THREAD

**Issue by jankoenig** [jovotech/jovo-cli#11]
Feature request in the [Jovo Slack](https://www.jovo.tech/slack): Users want to be able to chain the `$ jovo get` and `$ jovo build --reverse` command to be able to directly import their Alexa Skill Interaction Model into a Jovo Language Model.

Suggestion: `$ jovo get alexaSkill --build --reverse`

**Comment by aswetlow** [comment]
Added in 1.0.11

Usage: 
$ jovo get alexaSkill --build --reverse
