### ISSUE TITLE
nodemon randomly return The port 3000 is already in use

### ISSUE THREAD

**Issue by kouz75** [jovotech/jovo-cli#120]
## I'm submitting a...

- [x] Bug report

since migration to Jovo CLI Version: 3.0.1.
When Jovo cli is start with -w option
It return   "The port 3000 is already in use." when project files are update too frequently.
  
### Error log
```
npm start
> xxx@1.0.0 start /xxx
> NODE_ENV=dev DEBUG=info jovo run -w 
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js --webhook --jovo-webhook --stage local`
This is your webhook url: https://webhook.jovo.cloud/xxxxxx

To open Jovo Debugger in your browser, enter .

[nodemon] restarting due to changes...
[nodemon] starting `node index.js --webhook --jovo-webhook --stage local`
[nodemon] restarting due to changes...
[nodemon] starting `node index.js --webhook --jovo-webhook --stage local`
[nodemon] restarting due to changes...
[nodemon] starting `node index.js --webhook --jovo-webhook --stage local`
  Error -----------------------------------------------------------------
   Code:
  EADDRINUSE
    Message:
  The port 3000 is already in use.
   Stack:
  Error: listen EADDRINUSE: address already in use :::3000
      at Server.setupListenHandle [as _listen2] (net.js:1270:14)
......
  
  Hint:
  You might already run Jovo in a different tab. If the port is used by a different application, you can either change the port number in src/index.js, or specify the port as an option, e.g. jovo run --port 3301
  
   ----------------------------------------------------------------------
```

**Comment by rubenaeg** [comment]
Hey @kouz75,

what language do you use in your project, TypeScript or JavaScript?

**Comment by kouz75** [comment]
Hi
It's in javascript.
I don't know if there is a link but I have reboot my Mac and the bug doesn't appear any more...

**Comment by rubenaeg** [comment]
In my experience, sometimes a node process is running in the background on port 3000, doing some background work, for example compiling typescript files (in your case it must've been something else). Rebooting your mac killed the process, another fix for this would be to kill it manually, if it keeps the port busy. 3000 is a common port, so this is not as surprising, however it shouldn't occur frequently. 
I'm closing this issue for now, but feel free to report any problems again!
