### ISSUE TITLE
Jovo CLI Issues since update to v3 - multiple stages w/ askProfile

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-cli#127]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

JOVO CLI should work the way the 2.x CLI worked when it comes to:
- multiple stages in `project.js`
- stage has `alexaSkill` that specifies a value for `askProfile`
- `build` with a `-d` flag should include bundle/deploy of zip to lambda

## Current Behavior

It seems that some of the functionality that was working in CLI 2.x does not work the same in v3.

Example 1:
I often build and deploy with a single command: `jovo build -p alexaSkill --stage dev -d`
In v3, the code is not deployed to lambda

Example 2:
When I do a separate deploy: `deploy -p alexaSkill --stage dev`
The model and skill info are deployed, but the lambda is not.
I now have to explicitly target lambda for it to deploy: `deploy -p alexaSkill --stage dev -t lambda`

Example 3:
It doesn't appear that the `askProfile` specified in `project.js` for the given stage is used. `default` is used instead.
(see log below)

### Error log
```
C:\dev>jovo build -p alexaSkill --stage dev -d

 jovo build:  Create and update platform specific files in /platforms folder
   >> Learn more: https://jovo.tech/docs/cli/build

  √ Initializing build process...
    √ Collecting platform configuration from project.js.
      Platforms: alexaSkill
    √ Collecting Jovo language model files from ./models folder.
      Locales: en
    √ Validating model files.
      √ en
  √ Updating Alexa Skill project files (stage: dev)
   Path: ./platforms/alexaSkill
    √ Updating Skill Manifest
      Path: ./platforms/alexaSkill/skill.json
    √ Updating Alexa Interaction Model
      Path: ./platforms/alexaSkill/models
      √ en-US
  > Deploying project...
    > Deploying Alexa Skill (stage: dev)
      × Updating Alexa Skill project for ASK profile default
        → [Error]: Cannot resolve profile [default]
        Deploying Interaction Model, waiting for build
 »   Error: There was a problem:
 »   Error: [Error]: Cannot resolve profile [default]
```

## Your Environment

* Jovo CLI version used: 3.0.4
* Operating System: Windows 10

**Comment by rmtuckerphx** [comment]
It is annoying to have to pass the ask-profile as a CLI param because that was part of the beauty of `project.js` but I did, now I am getting a different error:

```
C:\dev>jovo deploy -p alexaSkill --stage=dev --ask-profile myprofile
  > Deploying Alexa Skill (stage: dev)
    × Updating Alexa Skill project for ASK profile myprofile
      → The trigger setting for the Lambda arn:aws:lambda:us-east-1:999999999999:function:myfunc-dev is invalid.
      Deploying Interaction Model, waiting for build
 »   Error: There was a problem:
 »   Error: The trigger setting for the Lambda arn:aws:lambda:us-east-1:999999999999:function:myFunc-dev is invalid.
```
What is meant by the trigger setting?

**Comment by jankoenig** [comment]
Looking into this.

Regarding the trigger setting. This happens when you try to deploy skill information that has a Lambda endpoint which is tied to a different Skill ID. Then the Alexa API throws an error.

**Comment by rubenaeg** [comment]
Hey @rmtuckerphx , 

does this error still occur?

**Comment by rubenaeg** [comment]
Closing this for now. If the issue still persists, feel free to reopen.
