### ISSUE TITLE
Error: command init not found

### ISSUE THREAD

**Issue by StErMi** [jovotech/jovo-cli#129]
## I'm submitting a...

- [x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
It should allow me to init the app.json file

## Current Behavior
I get the console error: 

```
Error: command init not found
```

## Your Environment

* Jovo CLI version used: jovo-cli/3.0.0 win32-x64 node-v12.0.0
* Operating System: Windows

**Comment by jankoenig** [comment]
Hi! app.json is now project.js
init command was only necessary in v1 projects

**Comment by StErMi** [comment]
Hi @jankoenig gotcha, you should update the cli doc and all the tutorials on the jovo site because they are still referring to it

**Comment by jankoenig** [comment]
which ones are referring to it? can't find it here: https://www.jovo.tech/docs/cli

are you maybe looking at the v1 docs?

**Comment by StErMi** [comment]
@jankoenig I was referring to the documentation that it's still available on the CLI GitHub page (README file): https://github.com/jovotech/jovo-cli
