### ISSUE TITLE
jovo get alexaSkill --> TypeError: Cannot read property 'locale' of undefined

### ISSUE THREAD

**Issue by StErMi** [jovotech/jovo-cli#130]
## I'm submitting a...
- [x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

I would expect to clone the app's platform from an alexaSkill

## Current Behavior

Get a cli error

### Error log
```
$ jovo get alexaSkill
 »   Error: There was a problem:
 »   TypeError: Cannot read property 'locale' of undefined
```

## Your Environment

* Jovo CLI version used: jovo-cli/3.0.0 win32-x64 node-v12.0.0
* Operating System: Windows

**Comment by rubenaeg** [comment]
Hi @StErMi,
the issue should be resolved in the current version of the Jovo CLI, `v3.0.5`. You can update with `npm install jovo-cli -g`.

**Comment by StErMi** [comment]
fixed, thanks @rubenaeg
