### ISSUE TITLE
More verbose error messages during --rebuild

### ISSUE THREAD

**Issue by Mistic92** [jovotech/jovo-cli#135]
## I'm submitting a...

- [X] Bug report
- [X] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Rebuild code from exported dialogflow agent

## Current Behavior
Crash during import without giving any additional info what might be wrong
I have 5 pages of intents in Dialogflow agent and it will be hard to find what might be wrong with this when I'm using build --reverse. I don't know what might be undefined, is this intent issue or paremeter issue. 

Can we add more verbose log with cause? 
### Error log
```
╰─ jovo build --reverse

 jovo build:  Create and update platform specific files in /platforms folder
   >> Learn more: https://jovo.tech/docs/cli/build

? Please select the platform you want to reverse build from: GoogleAction with DialogFlow (googleAction)
  ❯ Building language model platform model
    ❯ Reversing model files
      ✖ pl
        → Cannot read property 'length' of undefined
        en
 ›   Error: There was a problem:
 ›   TypeError: Cannot read property 'length' of undefined
```

## Your Environment

* Jovo CLI version used: 3.0.13
* Operating System: Windows 10 WSL2

**Comment by rubenaeg** [comment]
We are currently in the process of releasing a new version with support for ask-cli@v2, which will also come with more verbose error messages.

**Comment by ngocht** [comment]
I am having the same issue and do not have an idea what causes this error.


 jovo build: Build platform-specific language models based on jovo models folder.
   >> Learn more: https://jovo.tech/docs/cli/build

  ❯ Building language model platform model
    ❯ Reversing model files
      ✖ de
        → Cannot read property 'length' of undefined
 ›   Error: There was a problem:
 ›   TypeError: Cannot read property 'length' of undefined

**Comment by rubenaeg** [comment]
Could you please provide your platform-specific model files you're trying to reverse build from, so I can reproduce the error? You can send me an email to ruben@jovo.tech if you'd like.

**Comment by ngocht** [comment]
> Could you please provide your platform-specific model files you're trying to reverse build from, so I can reproduce the error? You can send me an email to [ruben@jovo.tech](mailto:ruben@jovo.tech) if you'd like.

I would love to but I am afraid I can not share the model file from my customer. happy to jump on a quick debug session via slack or zoom ...
