### ISSUE TITLE
Error: env: node\r: No such file or directory

### ISSUE THREAD

**Issue by majapersson** [jovotech/jovo-cli#140]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Running jovo after installing the CLI should not give an error.

## Current Behavior

Installed jovo-cli@3.0.11 globally using both yarn and npm. The installation runs fine, but running the CLI gives an error. Seems to be related to line endings, but it doesn't give me any information about where. Probably related to [this closed issue](https://github.com/jovotech/jovo-framework/issues/35) on the jovo-framework repo.

### Error log
```
$ jovo -v
env: node\r: No such file or directory
```

## Your Environment

* Jovo CLI version used: 3.0.11
* Node version: 12.16.3
* Operating System: macOS Mojave 10.14.6

**Comment by jankoenig** [comment]
Hi @majapersson, investigating this. Tried to reproduce with this system: `jovo-cli/3.0.11 darwin-x64 node-v12.16.3`

The `jovo` and `jovo -v` both work for me though. Will dig deeper

**Comment by krokben** [comment]
Okay I just fixed it by installing dos2unix with `brew install dos2unix`, then going to `user$/.config/yarn/global` and writing `dos2unix -F node_modules/.bin/*.` in the terminal. Look at this issue for more info:
https://github.com/yarnpkg/yarn/issues/5480

**Comment by majapersson** [comment]
That fixed it for me as well. Thank you @krokben! 🙏
