### ISSUE TITLE
"node index.js" doesn't run server as advertised

### ISSUE THREAD

**Issue by peternann** [jovotech/jovo-cli#15]
Hi guys.
The doco here: https://www.jovo.tech/framework/docs/cli#jovo-run

Suggests that "node index.js" is an "alternative" to 'jovo run'.

But for me "node index.js" just immediately **_exits, silently_**.

Looking at a 'ps af', the command line ultimately running under 'jovo run' is:
`node ./index.js --ignore db/* --webhook --jovo-webhook`

Running that commandline **does** run the service, but it **doesn't** put the 'webhook.jovo.cloud' tunnelling proxy in place (I assume that's handled by the 'jovo' CLI)

What I am _trying_ to do is run my webhook under the vscode debugger.

What would make that really easy is two suggestions:
1) A jovo CLI command to _just_ run the default proxy. (I assume it works a lot like ngrok...)
2) More accurate doco on how to really run the local default web service. i.e. Not "node index.js" which doesn't seem to work as advertised.

Thanks guys!

**Comment by jankoenig** [comment]
Thank you @peternann, you're correct, we missed to update that with the update.
The alternative to jovo run is `node index.js --webhook`.

@aswetlow also added an option which you can use for debugging in VS Code: `node index.js --webhook --inspect`. We're working on a tutorial that walks through all the steps to use it with the VS Code debugger.

**Comment by peternann** [comment]
Great. Thanks Jan.

But is there any way to run the default tunnelling proxy separately? (The webhook.jovo.cloud/[uuid] mechanism)
Or is there some complexity I am missing...

I could setup bst or ngrok myself, but it would be most convenient to continue using the default that 'jovo run' gives me.

**Comment by jankoenig** [comment]
You're right, this should work. I'll check in with @aswetlow and will get back to you with a solution. Thanks for the feedback!

**Comment by aswetlow** [comment]
Hey @peternann 
Debugging with vscode works as follows:
`jovo run --inspect` 

Debug (launch-config) in vscode: 
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Attach",
            "port": 9229
        },
    ]
}
```
Let me know if it helped

**Comment by peternann** [comment]
Thanks @aswetlow. That looks neat. I will give it a try later. Though I think that needs manual restarts on code changes, right?
With modern tooling, we can do better...

I want to control my own life-cycle of the webhook code itself - I plan to use Typescript, and I plan to use nodemon to achieve automatic restarts on code changes.

For both these reasons, I ask again:
Is there a way to **_just_** fire up your default tunnelling proxy (and leave it up), or is there some complication that I am missing? If not, could you add such a feature?

If it's non-trivial, that's fine, just let me know, and I will try out the bst proxy.

P.S. Can I also make a general suggestion - Online threads reach a conclusion much quicker if each response aims to address all questions/requests/suggestions from the OP. Even if the answer is "no" or "I'll look into it". ...Having to ask 3 times just drags things on...
Meant to be a friendly suggestion! Cheers!

**Comment by aswetlow** [comment]
> Though I think that needs manual restarts on code changes, right?
`jovo run --watch` starts nodemon. Just tried `jovo run --inspect --watch` and it worked. You don't have to rerun `jovo run` on changes, but (in my case) I have to restart my debugging monitor in my IDE.  

> Is there a way to just fire up your default tunnelling proxy (and leave it up), or is there some complication that I am missing? If not, could you add such a feature?
Could make sense. Let me come back to it tomorrow.

**Comment by aswetlow** [comment]
Sry, was working on an update to run the tunnelling separately. I will publish it tomorrow.

**Comment by peternann** [comment]
`jovo run --webhook-only` seems to be working nice! Thanks!

I can't test `jovo run --inspect --watch` sorry - I've already switched my source tree to Typescript.
;-(
I might setup a Typescript "Hello World" for you guys one day... I'm on a bit of a Typescript crusade... Even Google are moving to it, have you noticed?

One minor thing I've noted too - The CLI uses the term "(jovo) webhook" to mean the proxy, it seems.
This could confuse a few devs who see **their node code** as "the webhook".
I do agree you are using the term consistently, but it is a bit ambiguous for someone coming from existing development.
... Just a small comment... Happy to have the proxy running separately. Thanks!
