### ISSUE TITLE
Can jovo-cli run with node 13?

### ISSUE THREAD

**Issue by Carleslc** [jovotech/jovo-cli#159]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

The `jovo` command running without errors using node v13.

## Current Behavior

I cannot run any `jovo` command using my default node version v13. Using node v8.17.0 it works as expected.

### Error log
`jovo -v`
```
jovo-cli/3.0.21 darwin-x64 node-v13.6.0
(node:75990) SyntaxError Plugin: jovo-cli: Unexpected token 'export'
module: @oclif/config@1.17.0
task: runHook init
plugin: jovo-cli
root: /Users/carleslc/.nvm/versions/node/v13.6.0/lib/node_modules/jovo-cli
See more details with DEBUG=*
    SyntaxError: Unexpected token 'export'
```

## Your Environment

* Node version: v13.6.0 (npm v6.14.4)
* Jovo CLI version used: 3.0.21
* Operating System: macOS Catalina 10.15.6

**Comment by aswetlow** [comment]
Hey @Carleslc 

I was able to reproduce it with node v13.6.0, it works with v13.13.0 though.

Do you mind updating to a more recent version?

**Comment by Carleslc** [comment]
Done! Working with latest v14.8.0 too.

Thank you.
