### ISSUE TITLE
jovo build is using dialogflow instead of conversational actions to build the model

### ISSUE THREAD

**Issue by acerbisgianluca** [jovotech/jovo-cli#167]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Hi guys! I want to migrate from dialogflow to Conversational Actions and I followed the [documentation](https://www.jovo.tech/marketplace/jovo-model/google-assistant#using-the-google-assistant-jovo-model-with-the-jovo-cli) which tells me to remove `'nlu': 'dialogflow'` from the project.js file.

I did it, but `jovo build` tells me that `[ERR] Please add a dialogflow property for input "count"`. That error message comes from the `jovo-model-dialogflow` which is not the model builder I want to use.

**Comment by aswetlow** [comment]
Hey @acerbisgianluca 

We're still in the process of implementing Conversational Actions. 

I'll give an update by the end of the week.

**Comment by acerbisgianluca** [comment]
Hey @aswetlow, now it's able to build the model, but it gives an error on deploy: `Error: There was a problem: »   TypeError: Cannot read property '0' of undefined`

**Comment by aswetlow** [comment]
Quick Update:

Here's the HelloWorld template:
`jovo new <project> --template google-conversational-actions-helloworld --locale en`

Please upgrate the CLI to the latest version (3.0.25)


It's still in alpha and we're looking for bugs and improvements.

**Comment by aswetlow** [comment]
Closing this now. Feel free to re-open, if the error still occurs.

**Comment by jankoenig** [comment]
Here's a tutorial if that's helpful: https://www.jovo.tech/tutorials/google-conversational-actions-getting-started
