### ISSUE TITLE
jovo get throws error "Cannot read property 'publishingInformation' of undefined"

### ISSUE THREAD

**Issue by maegnes** [jovotech/jovo-cli#169]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Import an existing alexa skill into my platforms directory. The project (hellworld template) was created using the "jovo new" command and is completely untouched.

## Current Behavior
Throws an error "→ Cannot read property 'publishingInformation' of undefined"

### Error log

jovo get alexaSkill --overwrite

 jovo get: Downloads an existing platform project into the platforms folder.
Learn more: https://jovo.tech/docs/cli/get

? Select your project: MY SKILL - 2020-09-30 amzn1.ask.skill.SKILL-ID
  ✖ Getting Alexa Skill project 
    → Cannot read property 'publishingInformation' of undefined
    Getting Alexa Skill model files and saving to ./platforms/alexaSkill/models
 ›   Error: There was a problem:
 ›   TypeError: Cannot read property 'publishingInformation' of undefined
/usr/local/lib/node_modules/jovo-cli/node_modules/@oclif/errors/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/jovo-cli/node_modules/@oclif/errors/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
`

## Your Environment
Jovo CLI Version: 3.0.24
Jovo packages of current project:
  jovo-db-filedb : 3.1.0
  jovo-framework : 3.1.0
  jovo-platform-alexa : 3.1.0
  jovo-platform-googleassistant : 3.1.0
  jovo-plugin-debugger : 3.1.0

OS: macOS Catalina (10.15.6)
Node: 12.18.14 (also tried it with 8.10)

**Comment by aswetlow** [comment]
Hmm, I can't reproduce it.

Here's what I did.

```
> jovo new testskill
> cd testskill
> jovo build -p alexaSkill
> jovo deploy -p alexaSkill
> jovo get alexaSkill --overwrite
```

**Comment by maegnes** [comment]
I guess I had some inconsistencies with my nvm/node setup. After a completely fresh setup of my whole node environment it works as expected.

Thanks, Alexa!

**Comment by aswetlow** [comment]
It's Alex :D

Nevermind... muscle memory. Happens all the time 😄
