### ISSUE TITLE
Entity display name ‘sys.any’ is not valid

### ISSUE THREAD

**Issue by rubenaeg** [jovotech/jovo-cli#181]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Building and deploying the language model with `@sys.any` should work as expected.

## Current Behavior
`jovo build` creates three entries for `@sys.any`, as if it was a custom entity.

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo CLI version used: 1.x.x
* Operating System:

**Comment by alexmelekhavets** [comment]
Hey there! Getting this issue for other `@sys.` stuff as well:
```
 [ERR] com.google.apps.framework.request.BadRequestException: Entity display name 'sys.date' is not valid, it may contain only the following: A-Z, a-z, 0-9, _ (underscore), - (dash). And it should start with a letter.
 ›   Entity display name 'sys.date-period' is not valid, it may contain only the following: A-Z, a-z, 0-9, _ (underscore), - (dash). And it should start with a letter.
```
A temporary workaround is to remove these generated entities
```
sys.any.json
sys.any_entries_en.json
sys.date.json
sys.date-period.json
sys.date-period_entries_en.json
sys.date_entries_en.json
```
from the `dialogflow_agent.zip` file manually and then you can import this archive via Export and Import in settings of the dialogflow console.
