### ISSUE TITLE
Feature: Add command to build an optimized lamda bundle

### ISSUE THREAD

**Issue by fgnass** [jovotech/jovo-cli#20]
As mentioned in #10 we use the following workflow to keep the lamda function as small as possible:

```
#!/bin/bash

set -e
mkdir -p platforms/lambda
cp -r app index.js package.json platforms/lambda

# exclude tests, snapshots and fixtures:
rm -rf platforms/lambda/app/__*

cd platforms/lambda
npm i --production

cd ../../
jovo deploy -t lambda --src platforms/lambda
```

This way all dev-dependencies, tests, models and platform specific files are excluded from the bundle. It would be great if jovo-cli provided a similar functionality out of the box.

**Comment by aswetlow** [comment]
Cool idea. We will integrate it.

**Comment by jankoenig** [comment]
What do you all think? Should these steps be done by default with every `$ jovo deploy --target lambda` or should it be a separate option? I think it makes sense to make this default

**Comment by fgnass** [comment]
The pattern of files to be ignored should probably be configurable, preferably via an `.lambdaignore` file.

**Comment by blforce** [comment]
I agree that this should happen for every lambda deployment. I also like the idea of a .lambdaignore file to override some defaults or maybe have it as an option in app.json?

**Comment by aonamrata** [comment]
Can we merge this feature in?

**Comment by jankoenig** [comment]
Done in `v2`: `npm run bundle` or `jovo deploy --target zip`
