### ISSUE TITLE
setSessionAttribute('x','y'), followed by getSessionAttribute('x') doesn't return 'y'

### ISSUE THREAD

**Issue by peternann** [jovotech/jovo-cli#21]
It seems that 'getSessionAttribute()' ONLY get values from the inbound request payload, and setSessionAttribute() ONLY sets values in the outbound response payload.

So a 'set', followed by a 'get' in code doesn't work as you'd expect.
This is quite surprising given the general understanding of get/set.

How did I hit this?
I tend to store Intent data immediately into session data, and then call lower level code to process the collection of information in session data. A bit of a 'blackboard' approach, potentially giving the app a bit of short-term memory if needed, similar to how humans work.
This breaks if we can't set+get into SessionAttributes whenever we want...

**Comment by jankoenig** [comment]
Thanks @peternann, this is correct. We should probably do something like this:
* Create a local `sessionAttributes` object from the incoming request
* Write any changes between request and response into that object
* Write this object into the response object when the emit is done

Let us see how much needs to be changed to fix this after the `v1.2'  launch next week. Until then, would it be possible for you to store the date in a local variable, e.g. with `this.memory = this.getSessionAttributes()`  in the `ON_REQUEST` handler? Maybe this could be a workaround

**Comment by peternann** [comment]
Yep. I'm storing in local variables for now and passing down into required functions.
What you said makes sense.

**Comment by jankoenig** [comment]
Hi @peternann, this was added to the latest release of the Jovo Framework: https://github.com/jovotech/jovo-framework-nodejs/pull/146
