### ISSUE TITLE
Lambda deployment is skipped when endpoint is an object

### ISSUE THREAD

**Issue by fgnass** [jovotech/jovo-cli#23]
The endpoint config in `app.json` can be either a [string or an object](https://github.com/jovotech/jovo-cli/blob/596b4859ab07f91b5a538ef9a19be9a3a275e538/helper/alexaUtil.js#L328), for example to support setups where Alexa uses a Lambda function and dialogflow an API Gateway URL. In this case the Lambda deployment is skipped, probably because the following check assumes a string: https://github.com/jovotech/jovo-cli/blob/596b4859ab07f91b5a538ef9a19be9a3a275e538/commands/tasks.js#L530

**Comment by fgnass** [comment]
The most elegant solution would probably be to call `AlexaHelper.isLambdaEndpoint()` here, but this would require `skill.json` to exist at this point in time. I'm not sure if this is a safe assumption.

**Comment by jankoenig** [comment]
Thanks @fgnass! We're going to look into this after our `1.2` release tomorrow

**Comment by aswetlow** [comment]
Added "host" object to app.json

Example:
```
...
"googleAction": {
		"endpoint": "<URL TO ENDPOINT>",
		"nlu": {
			"name": "dialogflow"
		},
		"dialogflow": {
			"projectId": "project123",
			"keyFile": "project123-2b49ce6239cb.json"
		},
		"host": {
			"lambda": {
				"arn": "arn:aws:lambda:us-east-1:XYZ"
			}
		}
	},
...
```

Works only with an ask-cli profile with the permissions to access the lambda function  :/.
