### ISSUE TITLE
No matching version found for @nlpjs/slot

### ISSUE THREAD

**Issue by Kyngo** [jovotech/jovo-cli#281]
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

To install the Jovo framework with its dependencies

## Current Behavior

When installing the Node dependencies, an error shows up saying that no matching version could be found for "@nlpjs/slot"

### Error log
```
$ jovo new Home

jovo new: Create a new Jovo project
  >> Learn more: https://jovo.tech/docs/cli/new

🔮 Welcome to the Jovo CLI Wizard

✔ Pick a preset: › default

🔧 Setting everything up

✔ Creating new directory Home/
  /Users/kyngo/Development/Home
✔ Downloading and extracting template
✔ Generating package.json
✖ Installing npm dependencies

x Error: --------------------------------------------------------------------------------
›
› Message:
›  Command failed: npm install
›  npm ERR! code ETARGET
›  npm ERR! notarget No matching version found for @nlpjs/slot@^4.22.2.
›  npm ERR! notarget In most cases you or one of your dependencies are requesting
›  npm ERR! notarget a package version that doesn't exist.
›
›  npm ERR! A complete log of this run can be found in:
›  npm ERR!     /Users/kyngo/.npm/_logs/2022-01-03T20_54_53_079Z-debug-0.log
›
›
› Module:
›  NewCommand
›
›
› If you think this is not on you, you can submit an issue here: https://github.com/jovotech/jovo-cli/issues.
```

## Your Environment

* Jovo CLI version used: 4.0.3
* Operating System: macOS Monterey (12.1)
* Node versions tested: 14 (x86 via Rossetta and arm64 compiled via nvm), 16 (arm64 compiled via nvm) - both instances fail with the same error
* @jovotech/cli/4.0.3 darwin-x64 node-v14.17.0
* @jovotech/cli/4.0.3 darwin-arm64 node-v14.18.2
* @jovotech/cli/4.0.3 darwin-arm64 node-v16.13.1

**Comment by aswetlow** [comment]
Hey @Kyngo 

There was a publishing problem with a dependency we use. According to this thread, the developers of nlpjs are working on it.
https://github.com/axa-group/nlp.js/issues/1031

If it's not fixed in a few hours, we'll try to downgrade to a lower version.

**Comment by Kyngo** [comment]
Alright! I'll keep an eye on that issue as well. Thanks for the help!

**Comment by Kyngo** [comment]
@aswetlow FYI - The repo has been fixed, it's now working as it should!

**Comment by aswetlow** [comment]
Haha, I came to tell you the same. 

Thanks
