### ISSUE TITLE
Alexa: "You do not have access to the resource"

### ISSUE THREAD

**Issue by alexanderkoller** [jovotech/jovo-cli#287]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

When executing `jovo deploy:platform alexa`, Jovo should deploy the skill to the Amazon Alexa Console.

## Current Behavior

Instead, I get the following error message:

```
(base) turing:jovotest koller$ jovo deploy:platform alexa
                                                                                
jovo deploy:platform: Deploy to the specified platform's developer console
  >> Learn more: https://jovo.tech/docs/cli/deploy-platform
                                                                                
🚀 Deploying Alexa Skill
  ✖ Uploading skill package
                                                                                
x Error: --------------------------------------------------------------------------------
›                                                                                 
› Message:
›  smapiImportSkillPackage: You do not have access to the resource.
›                                                                                 
› Module:
›  AlexaCli
›                                                                                 
›                                                                                 
› If you think this is not on you, you can submit an issue here: https://github.com/jovotech/jovo-cli/issues.
```

This is after executing build:platform and the other steps [described in the documentation](https://www.jovo.tech/marketplace/platform-alexa).

I have previously managed to deploy the exact same skill with deploy:platform, but that was with another Amazon Developer account. (I switched accounts so I could test the skill on an Echo device.) I have deleted the ask-cli configuration and rerun `ask configure`.

The [only reference](https://medium.com/aeturnuminc/getting-started-with-alexa-skill-kit-command-line-interface-ask-cli-2555bcfefbd1) for that error message that I can find online suggests that I should explicitly specify the ask-cli profile, but I get the same error with `jovo deploy:platform alexa --ask-profile default`. There is also a [brief discussion](https://community.jovo.tech/t/new-error-seen-on-jovo-build-reverse-on-windows-10/1123) in the context of Jovo, but that seems to apply to upgrading Jovo versions.

Have you seen this error message before? Is there something Jovo-specific, beyond reconfiguring the ASK CLI, that I need to do when I switch Alexa developer accounts?

## Your Environment

```
(base) turing:jovotest koller$ jovo -v
                                                                                
@jovotech/cli: 4.0.3 

Jovo packages of the current project (updates available):
  - @jovotech/cli-command-build: 4.0.1
  - @jovotech/cli-command-deploy: 4.0.1
  - @jovotech/cli-command-get: 4.0.1
  - @jovotech/cli-command-new: 4.0.1
  - @jovotech/cli-command-run: 4.0.1
  - @jovotech/cli-core: 4.0.1
  - @jovotech/common: 4.0.2 -> 4.0.3
  - @jovotech/db-filedb: 4.1.1 -> 4.1.2
  - @jovotech/filebuilder: 0.0.1
  - @jovotech/framework: 4.1.1 -> 4.1.2
  - @jovotech/model: 4.0.0
  - @jovotech/model-alexa: 4.0.0
  - @jovotech/model-nlpjs: 4.0.0
  - @jovotech/nlu-nlpjs: 4.1.1 -> 4.1.2
  - @jovotech/output: 4.0.2 -> 4.0.3
  - @jovotech/platform-alexa: 4.1.1 -> 4.1.2
  - @jovotech/platform-core: 4.1.1 -> 4.1.2
  - @jovotech/plugin-debugger: 4.1.1 -> 4.1.2
  - @jovotech/server-express: 4.1.1 -> 4.1.2

Use "jovo update" to get the newest versions.
                                                                                
Environment:
  System:
    OS: macOS 11.4
  Binaries:
    Node: 14.15.2 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
```

My `jovo.project.js` looks as follows:

```
const { ProjectConfig } = require('@jovotech/cli-core');
const { AlexaCli } = require('@jovotech/platform-alexa');

/*
|--------------------------------------------------------------------------
| JOVO PROJECT CONFIGURATION
|--------------------------------------------------------------------------
|
| Information used by the Jovo CLI to build and deploy projects
| Learn more here: www.jovo.tech/docs/project-config
|
*/
const project = new ProjectConfig({
  endpoint: '${JOVO_WEBHOOK_URL}',
  plugins: [
    new AlexaCli({
      locales: {
        en: ['en-US', 'en-GB'],
        de: ['de-DE']
      }
    })
    // Add Jovo CLI plugins here
  ],
});

module.exports = project;
```

**Comment by alexanderkoller** [comment]
Update: In a fresh clone of my repository, I don't get the same error - the deployment runs without a problem. This confirms my hypothesis that Jovo stores something about my Amazon developer account somewhere. Is there a way to delete that when switching to a different developer account?

**Comment by rubenaeg** [comment]
The Skill Id is stored inside `build/platform.alexa/.ask/ask-states.json`, you could run `jovo build:platform alexa --clean`, which will remove your previously built files and build a clean version.

**Comment by alexanderkoller** [comment]
That's good to know, thanks!

**Comment by jankoenig** [comment]
Thanks! I just updated the docs a bit to make that clearer: https://github.com/jovotech/jovo-framework/pull/1173/commits/b3a34407961a78ef9bb427376501a29173fb9c53
