### ISSUE TITLE
Type property didnt trigger handler

### ISSUE THREAD

**Issue by alvarocardenasc** [jovotech/jovo-cli#296]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

it should trigger playbackStopped handler.
```
@Types('AudioPlayer.PlaybackStopped')
 playbackStopped() {
        console.log('====>>>PLAYBACKSTOPPED TYPE AUDIO PLAYER====');
    }
```

## Current Behavior

the handler never gets executed

### Error log
```
MatchingRouteNotFoundError.

Alexa Request:
"request": {
        "type": "AudioPlayer.PlaybackStopped",
        "requestId": "xxxxx",
        "timestamp": "2022-01-27T14:45:48Z",
        "locale": "en-US",
        "token": "a",
        "offsetInMilliseconds": 24732
    }
```

What I'm missing?

## Your Environment

* Jovo CLI version used: 4.0.3
* Operating System: macOS 10.15.5

**Comment by jankoenig** [comment]
Is this handler in a global component?

btw, we just released audioplayer support: https://www.jovo.tech/marketplace/platform-alexa/audioplayer

**Comment by alvarocardenasc** [comment]
No it's in my own AudioPlayerComponent. it should be in a global component?
Nice for the release of AudioPlayer support, I will use it.

**Comment by jankoenig** [comment]
Yes, or you can make that handler global. audioplayer requests don't come with state data
