### ISSUE TITLE
app.json filename conflicts with Heroku's app.json

### ISSUE THREAD

**Issue by wyantb** [jovotech/jovo-cli#30]
The naming of the `app.json` file as used by jovo conflicts with Heroku's [`app.json` file](https://devcenter.heroku.com/articles/app-json-schema), which has very different configuration options specified. Can jovo support alternate paths to this file? Perhaps `${projectDir}/jovo-app.json` or `${projectDir}/.jovo/app.json` or similar. I'm also open to needing to specify a file for each run command, like `--config jovo-app.json`

**Comment by aswetlow** [comment]
You're right. Currently, It's not possible :/
We will fix it soon.

**Comment by rmtuckerphx** [comment]
Should rename app.json file to jovo-build.json

**Comment by jankoenig** [comment]
Done. Renamed to `project.js` in `v2`
