### ISSUE TITLE
Unable to reverse and rebuild on google platform

### ISSUE THREAD

**Issue by jbjfromont** [jovotech/jovo-cli#31]
I started a new agent on Dialogflow v2 recently, and I choose jovo framework to build and deploy my agent easily. 

When my agent was done I exported it, and then placed it into the platform folder to generate the {local}.json (by using `jovo build --platform googleAction --reverse`). Then I built it, and deployed it in Dialogflow (with `jovo  build --platform googleAction --deploy`).
But that broke my agent, all my intent that used an entity was no longer recognizing them. I went in the platform folder and the file changed, especially the files {intent}_usersays_{local}.json : the word defined by the user (which are my entities) are still separated from the others, but no longer have the fields "alias" and "meta", for exemple : 

```
  {
    "id": "   .   .   .   ",
    "data": [
      {
        "text": "My name is ",
        "userDefined": false
      },
      {
        "text": "Jason",
        "alias": "name",
        "meta": "@name",
        "userDefined": true
      }
    ],
    "isTemplate": false,
    "count": ....,
    "updated": ...
  },
```
became : 

```
  {
    "data": [
      {
        "text": "My name is ",
        "userDefined": false
      },
      {
        "text": "Jason",
        "userDefined": true
      }
    ],
    "isTemplate": false,
    "count": ....,
  },
```
I understand that by replacing "Jason" by "name" it should works, but I don't really want to replace all the names, or numbers in my intents by "name" and "number" (I think it is easier to read an intent as : "My name is jason", than :  "My name is name", and more understandable for someone who will have to change it, or add more example). 

My question is : is it really needed to change all my entities values in my intents by their name, and if so shouldn't the `jovo build --platform googleAction --reverse` automatically replace them ?

**Comment by aswetlow** [comment]
Thanks @jbjfromont,
yes, it was a bug. Should be fixed now.
