### ISSUE TITLE
Jovo deploy:code serverless --stage  Not Working

### ISSUE THREAD

**Issue by alvarocardenasc** [jovotech/jovo-cli#310]
## I'm submitting a...

- [x] Bug report
- [x] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

`jovo deploy:code serverless --stage prod`

opt:stage variable should be prod not dev.

serverless.yaml:
`"provider":
  "name": "aws"
  "runtime": "nodejs14.x"
  "region": "us-west-2"
  "stage": "${opt:stage,'dev'}"
  "apiName": "jovoDemoApi-${opt:stage,'dev'}"
`

What I'm missing?

## Current Behavior

stage in serverless is dev instead of prod.

### Error log
```
```

## Your Environment

* Jovo CLI version used: 4.1.0
* Operating System:10.15.5

**Comment by aswetlow** [comment]
Thanks for flagging. Working on a fix

**Comment by jankoenig** [comment]
Hey @alvarocardenasc, a workaround could be to use the following commands instead of `jovo deploy:code serverless`:

- `npm run bundle:prod`
- `serverless deploy --stage prod`
