### ISSUE TITLE
Intent inside component not triggering

### ISSUE THREAD

**Issue by alvarocardenasc** [jovotech/jovo-cli#321]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

trigger intents inside current component.

## Current Behavior

After I launched an audioPlayer, intents like AMAZON.PauseIntent,AMAZON.NextIntent etc inside the same component dont trigger unless I set them as global.

### Error log
```
```
In the previous jovo version 4.1.1 that was working fine.

## Your Environment

* Jovo CLI version used: 4.1.3
* Operating System: 10.15.5

**Comment by jankoenig** [comment]
When AudioPlayer starts a song, the session ends. This is why new requests are seen as new sessions, so the handlers need to be global.

Learn more here: https://www.jovo.tech/marketplace/platform-alexa/audioplayer#audioplayer-handlers
