### ISSUE TITLE
i18n Array

### ISSUE THREAD

**Issue by alvarocardenasc** [jovotech/jovo-cli#323]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

"translation": {
        "hello": ["Hello!", "Hi", "Howdy!"]
}
messageSSML = `${this.$t('hello')}`;

///Say only one of the elements in the array

## Current Behavior

it sends: Hello!,Hi,Howdy!   instead of only one option.

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo CLI version used: 4.1.3
* Operating System: Mac 10.15.5

**Comment by jankoenig** [comment]
Hi! `$t` returns an array. The `message` and `reprompt` properties are then randomized based on the array. Learn more here: https://www.jovo.tech/docs/i18n#arrays-and-randomization

If you want to randomize a different element, you can use this helper https://www.jovo.tech/docs/output-helpers#randomize
