### ISSUE TITLE
Jovo Deploy to lambda does nothing

### ISSUE THREAD

**Issue by mastacheata** [jovotech/jovo-cli#35]
## I'm submitting a...

- [ x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

jovo deploy -t lambda
should do anything. Either create the zip file for manual deployment or better yet deploy the skill to AWS lambda directly.

## Current Behavior

`λ  jovo deploy -t lambda

   √ Deploying Alexa Skill

  Deployment completed.`

The AWS Lambda dashboard shows that the corresponding function wasn't updated in the last hour (that was when I last updated it by hand).

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 1.2.1
* Operating System: Win 10 x64 Build 1803

**Comment by aswetlow** [comment]
Hey @mastacheata, 
could you post your app.json?

**Comment by mastacheata** [comment]
Sure:
```
{
    "alexaSkill": {
        "nlu": "alexa"
    },
    "endpoint": "https://webhook.jovo.cloud/be253948-a556-49c5-954e-18e24a71207b"
}
```

I also tried to add a host to the alexaSkill, because that was recommended in another issue, but to no avail:
```
{
	"alexaSkill": {
		"nlu": "alexa",
		"host": {
			"lambda": {
				"arn": "arn:aws:lambda:eu-west-1:767171228215:function:videorecorderEnFunc"
			}
		}
	},
	"endpoint": "https://webhook.jovo.cloud/be253948-a556-49c5-954e-18e24a71207b"
}
```

**Comment by aswetlow** [comment]
Looks fine to me. Could you try it with the ask cli? Just to make sure we don't miss an error message.
`ask lambda upload -f arn:aws:lambda:eu-west-1:767171228215:function:videorecorderEnFunc`

**Comment by jankoenig** [comment]
Hi @mastacheata , jovo-cli `v1.1.10` should fix this
