### ISSUE TITLE
Dialogflow's headers are lost while importing to jovo

### ISSUE THREAD

**Issue by jbjfromont** [jovotech/jovo-cli#36]
Hello,
I have an agent in dialogflow, and I need some headers to connect it with a lambda (using an API Gateway).
When I export the agent with dialogflow my headers are in the agent.json stored like that : 

```
...
 "webhook": {
    "url": "my-endpoint . . . ",
    "headers": {
      "my-header": "header-value",
      "another-header": " . . ."
    },
...
```

  The problem is that if I build the language model (by using : `jovo build --reverse` ) and then rebuild the platform (with : `jovo build` ) the headers disapears and my agent.json became like that : 

```
...
 "webhook": {
	"url": "my-endpoint . . .",
        ...
 },
...
```
I did not found a way to set the headers in app.json (like the endpoint), is there any way to set them ?

**Comment by aswetlow** [comment]
Hey @jbjfromont,
just fixed it in v1.1.5

**Comment by jbjfromont** [comment]
Thanks for this fix (that solved the problem as I explained it), but I still have a problem : 
I use the headers to give an api key to API Gateway, to control the API usage.
I have different lambda depending on the stage I want to work with (for example one stage to develop my agent and another one designed to be accessible to the public).

I can manage the different endpoint in the app.json (by using the stages, and it works like a charm), but I would like to give different API key depending on the stages (as my endpoint is different by stage). My problem is that with the current solution I am not able to do so.

**Comment by aswetlow** [comment]
This should work: 
```
"googleAction": {
				"dialogflow": {
					"agent": {
						"webhook": {
							"headers": {
								"headerKey": "headerValue"
							}
						}
					}
				}
			},
```

**Comment by jbjfromont** [comment]
Thank you, exactly what I wanted. Sorry I didn't noticed that I could do it this way !
