### ISSUE TITLE
Allow app.json to override interactonModel

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-cli#42]
## I'm submitting a...

- [ ] Bug report
- [X] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Allow app.json to override part of the interactonModel. For a dev stage, I might want the invocationName to be "hello world dev" and for a qa stage, "hello world qa"

## Current Behavior

In app.json you can override part of the skill.json by specifying a manifest node.
Not currently available for model.

### Error log
```
none
```

## Your Environment

* Jovo CLI version used: 1.1.6
* Operating System: Windows 10

**Comment by aswetlow** [comment]
Added to Jovo CLI 1.1.9
Thanks @rmtuckerphx

**Comment by aswetlow** [comment]
Example: 
```
"stages": {
	"dev": {
		"languageModel": {
			"en-US": {
				"invocation": "my test app dev",
			}
		}
	},
	"prod": {
		"languageModel": {
			"en-US": {
				"invocation": "my test app prod"
			}
		}
	}
},


```

**Comment by aswetlow** [comment]
Yes, that will work.
