### ISSUE TITLE
Convert entities from model to alexa/googleAction  with id 

### ISSUE THREAD

**Issue by kouz75** [jovotech/jovo-cli#53]
## I'm submitting a...

- [ x] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

I don't know if it's a bug or something is missing is the doc but I don't find the good way to write an inputTypes for alexa/DF with id

## Expected Behavior
Current inputType isn't convert correctly for alexa/dialogflow 
`
"inputTypes": [
			{
			"name": "Prenom",
			"values": [
				{
					"id": "p1",
					"value": "Gabriel"
				}
                        ]}]
`
For alexa I will have the current type:

`"values": [
	{
		"id": "p1",
		"name": {
			"value": "Gabriel"
		}
	}
]
`
For DF I should expect to get 
`	
       {
		"value": "p1",
		"synonyms": [
			"Gabriel"
		]
	},
`

## Current Behavior

For DF:
`	
       {
		"value": "Gabriel",
		"synonyms": [
			"Gabriel"
		]
	},
`

If I want to have the id p1 in DF, I need to structure the model like this:
`
{
	"id": "p1",
	"value": "p1",
	"synonyms": ["Gabriel"]
},
`
then DF entites will have following structure which is not really optimize

`
"value": "p1",
		"synonyms": [
			"p1",
			"Gabriel"
		]
`
and alexa 
`
{
	"id": "p1",
	"name": {
		"value": "p1",
		"synonyms": [
			"Gabriel"
		]
	}
}
`

Jovo CLI Version: 1.2.0

**Comment by rubenaeg** [comment]
Closing this for now due to inactivity. If the issue still persists, feel free to reopen.
