### ISSUE TITLE
pt-BR model create only pt and not pt-BR on Dialogflow

### ISSUE THREAD

**Issue by renatoalencar** [jovotech/jovo-cli#54]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

When deploying a `pt-BR` model to Dialogflow it should deploy strictly `pt-BR`, or at least, provide an option to do it this way.

## Current Behavior

Deploying a model in `pt-BR` leads to a `pt` model in Dialogflow instead of `pt-BR`. The problem is that the Actions on Google simulator, for example, does not support `pt` only `pt-BR`. This behavior is caused by the pieces of code listed below.

[dialogflowUtil.js lines 141-144](https://github.com/jovotech/jovo-cli/blob/master/helper/dialogflowUtil.js#L141-L144)
```javascript
if (findings.length === 1) {
    delete supportedLanguages[locale.toLowerCase()];
    supportedLanguages[locale.toLowerCase().substr(0, 2)] = '';
}
```

[dialogFlowAgent.js lines 308-310](https://github.com/jovotech/jovo-cli/blob/master/helper/dialogFlowAgent.js#L308-L310)
```javascript
if (primLanguage.length === 1) {
    outputLocale = this.config.locale.substr(0, 2);
}
```

I think I understood the purpose of these behaviors, makes a lot of sense for English off course. But for Portuguese, it think it is more complex. Brazilian Portuguese is far more adopted by platforms and is the only option available on Actions on Google simulator which leads to an error when trying to use European Portuguese on it.

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo CLI version used: 1.2.1
* Operating System: macOS High Sierra 10.13.4

**Comment by renatoalencar** [comment]
If you guys understand this as an error, I could send a Pull Request based on your feedbacks. Thanks.

**Comment by jankoenig** [comment]
Hi @renatoalencar, thanks for spotting this. Yes, would love to get this as a Pull Request! Thanks a lot 👍

**Comment by renatoalencar** [comment]
What do you think that would be the best solution, remove those lines of code or enable/disable it using a command line option?

**Comment by aswetlow** [comment]
Hey @renatoalencar 
We just fixed it with some other issues. Please update to cli version 1.2.2
