### ISSUE TITLE
Reserved characters not removed when generating Dialogflow v2 entity value synonyms

### ISSUE THREAD

**Issue by IGx89** [jovotech/jovo-cli#55]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Steps to Reproduce
1. Create an input type with a value that contains parentheses. For example:
```
{
	"name": "LOCATION_LIST",
	"values": [
		{
			"value": "Crosstown (Eden Prairie)",
			"synonyms": [
				"Crosstown"
			]
		}
	]
}
```

2. Do a build and deploy to Dialogflow v2 using Restore From Zip

## Expected Behavior
No error message when restoring from zip in the Dialogflow console, and a value named "Crosstown (Eden Prairie)" with synonyms "Crosstown Eden Prairie" and "Crosstown" under the LOCATION_LIST entity in Dialogflow.

## Current Behavior
The error message `Error parsing Entity 'LOCATION_LIST': Syntax Error in input 'Crosstown (Eden Prairie)'. Incorrect token '(' at position 10. Brackets can only be used with parameterized entities.` is shown and continues to show when I attempt to save the model. There's also a value named "Crosstown (Eden Prairie)" with synonyms "Crosstown (Eden Prairie)" and "Crosstown" under the LOCATION_LIST entity in Dialogflow. Voice training never happens.

See https://stackoverflow.com/questions/50037978/dialogflow-adding-entity-values-with-brackets for a little more details on this issue. The parenthesis, characters not allowed in entity reference value synonyms in Dialogflow, basically just need to be removed when building.

**Comment by aswetlow** [comment]
Hey @IGx89 
Fixed it. Invalid characters will be removed from synonyms.

**Comment by IGx89** [comment]
Thanks Alex! I've confirmed it works now in v1.2.3. Only slight concern is that hyphens ("-") are now removed when Dialogflow seems to be OK with them in synonyms, however I have no evidence of that being a bad thing, yet. Main concern would be with hyphenated names, like "Anglo-Saxon", that are now "AngloSaxon" -- don't know if that affected recognition or not.

**Comment by aswetlow** [comment]
Fixed it! Thanks :)
