### ISSUE TITLE
adm-zip in package.json is out-of-date and has a security vulnerability

### ISSUE THREAD

**Issue by jbmadscience** [jovotech/jovo-cli#61]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
npm audit reports no security vulnerabilities

## Current Behavior
npm audit reports that adm-zip has a "high" severity vulnerability, which was patched in adm-zip 0.4.9.
The current version of adm-zip in package.json is 0.4.7.

### Error log
                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  High            Arbitrary File Write via Archive Extraction

  Package         adm-zip

  Patched in      >=0.4.9

  Dependency of   jovo-cli [dev]

  Path            jovo-cli > adm-zip

  More info       https://nodesecurity.io/advisories/681

  Low             Prototype Pollution

  Package         lodash

  Patched in      >=4.17.5

  Dependency of   jovo-cli [dev]

  Path            jovo-cli > vorpal > inquirer > lodash

  More info       https://nodesecurity.io/advisories/577

found 2 vulnerabilities (1 low, 1 high) in 3884 scanned packages
  2 vulnerabilities require manual review. See the full report for details.

## Your Environment
* Jovo CLI version used: 1.2.5

I would be glad to update adm-zip in package.json, but first wanted to make sure that isn't expected to cause any issues with the project.

**Comment by aswetlow** [comment]
hey @jbmadscience 
adm-zip 0.4.9 failed in tests, but 0.4.11 passed. We updated it together with lodash in Jovo CLI 1.2.6. Thanks!

**Comment by jbmadscience** [comment]
Looks like this is addressed then, thanks!
