### ISSUE TITLE
Timout error on request

### ISSUE THREAD

**Issue by photonfighter** [jovotech/jovo-cli#7]
Every time I do jovo run and then use amazon dev console to test the skill, I get this:

```
This is your webhook url: https://webhook.jovo.cloud/... my webhook id would go here
Example server listening on port 3000!
Timeout error: No response after 5000 milliseconds
Unhandled Rejection at: Promise Promise {
  <rejected> { Error: socket hang up
    at createHangUpError (_http_client.js:335:15)
    at Socket.socketCloseListener (_http_client.js:367:23)
    at Socket.emit (events.js:132:15)
    at Socket.emit (domain.js:421:20)
    at TCP._handle.close [as _onclose] (net.js:550:12) code: 'ECONNRESET' } } reason: { Error: socket hang up
    at createHangUpError (_http_client.js:335:15)
    at Socket.socketCloseListener (_http_client.js:367:23)
    at Socket.emit (events.js:132:15)
    at Socket.emit (domain.js:421:20)
    at TCP._handle.close [as _onclose] (net.js:550:12) code: 'ECONNRESET' }
Timeout error: No response after 5000 milliseconds
Unhandled Rejection at: Promise Promise {
  <rejected> { Error: socket hang up
    at createHangUpError (_http_client.js:335:15)
    at Socket.socketCloseListener (_http_client.js:367:23)
    at Socket.emit (events.js:132:15)
    at Socket.emit (domain.js:421:20)
    at TCP._handle.close [as _onclose] (net.js:550:12) code: 'ECONNRESET' } } reason: { Error: socket hang up
    at createHangUpError (_http_client.js:335:15)
    at Socket.socketCloseListener (_http_client.js:367:23)
    at Socket.emit (events.js:132:15)
    at Socket.emit (domain.js:421:20)
    at TCP._handle.close [as _onclose] (net.js:550:12) code: 'ECONNRESET' }
```

Not really sure what this is about. I'm running node 9.6.1 and jovo-cli 1.0.4. My skill does make a http get request, but even if I comment all of that out and uninstall the package for that (node-rest-client), I still get this. I'm new to jovo, so I don't have any examples of this working before.

**Comment by rv-ekramer** [comment]
Are you using ‘this.tell(stringToSay)’ or ‘this.ask(stringToAsk)’ anywhere in your intents? I’ve found not doing this has often caused this error

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by photonfighter** [comment]
Yeah, here's my app.js:

```
'use strict';

// =================================================================================
// App Configuration
// =================================================================================

const {App} = require('jovo-framework');
// var Client = require('node-rest-client').Client;
// var client = new Client();

const config = {
    logging: true,
};

const app = new App(config);

const COOL = 0;
const HEAT = 1;


// =================================================================================
// App Logic
// =================================================================================

app.setHandler({
    'LAUNCH': function() {
        const heatCoolStatus = COOL;
        if (heatCoolStatus === COOL) {
          this.tell('If you turn on your system, it will cool your room.');
        } else if (heatCoolStatus === HEAT) {
          this.tell('If you turn on your system, it will heat your room.');
        } else {
          throw console.error();
        }

    },

    'NEW_USER': function() {
      this.ask('Hi, I\'m the ghost of Helen Peabody. I\'m not as scary as they say. Right now, all I can do is tell you if your heating cooling system will heat or cool your room, but I\'m learning how to do new things all the time.');
    },
});

// function getHeatCoolStatus () {
//
//
//   client.get("http://api.openweathermap.org/data/2.5/weather?zip=45056,us&units=imperial&APPID=my api key would go here", function (data, response) {
//     var temp = data.main.temp;
//
//     if(temp < 55.0) {
//       return HEAT;
//     } else {
//       return COOL;
//     }
//   });
//
// }

module.exports.app = app;
```

I haven't actually made any custom intents yet, but should I make one for LAUNCH to redirect to?

**Comment by rv-ekramer** [comment]
Huh. Weird that you’re getting that error. One thing that comes to mind is it doesn’t like you’re constants being well, constants instead of strings. Maybe try changing it to say ‘if(heatCoolStatus === “COOL”)’, just for the sake of debugging to see what happens.

It shouldn’t matter that you don’t have any custom intents but you could try, also as a part of debugging, to separate the logic in the LAUNCH intent to a custom WELCOME intent (or whatever you want to call it) and then use ‘this.toIntent(‘WELCOME’)’ in your LAUNCH intent instead and see what that does.

Also I don’t think this is necessary either, but after you create the custom intent the code I would go to the Alexa Developer console where you edit your skill and add custom intents and add the WELCOME intent their too.

If none of this work, comment out your if statement and make the only thing that the LAUNCH intent does is ‘this.tell(‘hello world’);’ (or some simple string)

If that works it’s a problem with your if statement.

If not, before assuming the issue is more involved than it is, I would double check the “Endpoints” section of the new Alexa Developer console and ensure that HTTPS is selected, has your Jovo webhook URL as the first entry in the list (the one that’s logged to your console as soon as you start the server with ‘jovo run’ or ‘jovo run —watch’)

Also make sure that from the drop down in the HTTPS section of the Endpoints tab, the option is selected that says something like “My domain is a sub domain of a domain that has a valid certificate”

Let me how things go

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by photonfighter** [comment]
Out of curiosity, I just decided to put a bunch of random characters in my app.js file, and to my surprise, I found no InvalidToken errors while running "jovo build" and "jovo run". I think something is seriously goofy here, it's like it's not even looking at app.js. 

I also commented out absolutely all of the logic I wrote except this.ask and this.tell stuff.

After double and triple checking that the models and the endpoints were correct, and trying this all again, it still built and run without any errors (despite having aksdjfs thrown in the app.js) and I still got the same timeout error.

This is some seriously spooky stuff. Maybe something of substance is that I am running this on Ubuntu on Windows, and I did have success doing much of the same thing on a Pi Zero W. It's also initialized as a git repository, if that would have anything to do with it.

Here's my current app.js: 

```
'use strict';

// =================================================================================
// App Configuration
// =================================================================================

const {App} = require('jovo-framework');
// var Client = require('node-rest-client').Client;
// var client = new Client();

const config = {
    logging: true,
};

const app = new App(config);

// const COOL = 0;
// const HEAT = 1;


// =================================================================================
// App Logic
// =================================================================================

app.setHandler({
    'LAUNCH': function() {
        // const heatCoolStatus = COOL;
        // if (heatCoolStatus === COOL) {
        //   this.tell('If you turn on your system, it will cool your room.');
        // } else if (heatCoolStatus === HEAT) {
        //   this.tell('If you turn on your system, it will heat your room.');
        // } else {
        //   throw console.error();
        // }

       this.toIntent('WelcomeIntent'); jkdfjsdfa

    },

    'WelcomeIntent': function() {
      this.tell('Hello there.');
    },

    'NEW_USER': function() {
      this.ask('Hi, I\'m the ghost of Helen Peabody. I\'m not as scary as they say. Right now, all I can do is tell you if your heating cooling system will heat or cool your room, but I\'m learning how to do new things all the time.');
    },
});

// function getHeatCoolStatus () {
//
//
//   client.get("http://api.openweathermap.org/data/2.5/weather?zip=45056,us&units=imperial&APPID=af96f11d0c240f04d811dcf6add4b929", function (data, response) {
//     var temp = data.main.temp;
//
//     if(temp < 55.0) {
//       return HEAT;
//     } else {
//       return COOL;
//     }
//   });
//
// }

module.exports.app = app;

```

And here's my model (not the one in the platform folder):

```
{
	"interactionModel": {
		"languageModel": {
			"invocationName": "helen's ghost",
			"types": [],
			"intents": [
				{
					"name": "WelcomeIntent",
					"samples": [
						"hello",
						"say hello",
						"say hello world"
					]
				},
				{
					"name": "AMAZON.CancelIntent",
					"samples": []
				},
				{
					"name": "AMAZON.HelpIntent",
					"samples": []
				},
				{
					"name": "AMAZON.StopIntent",
					"samples": []
				}
			]
		}
	}
}
```

**Comment by rv-ekramer** [comment]
Weird stuff man. I'm not sure what's going on. If I were you I'd uninstall jovo-cli and reinstall it. I've also found you might need jovo installed too (in addition to jovo-cli) and then when its re-installed try running `jovo new helloWorld` and try doing the same thing, putting random characters in the app.js and see if that new app throws an error.


If that new app doesn't work I'd just say wait for a member of the core jovo-cli team to respond and sorry I couldn't help.

________________________________

**Comment by photonfighter** [comment]
No luck, but thanks for your help anyway! I think that this process narrowed everything down to an issue with Ubuntu on Windows, but I'm not entirely sure on that. Like you say, we'll see what the dev team has to say.

**Comment by rv-ekramer** [comment]
You’re welcome, sorry I couldn’t help. But at least we narrowed down the issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aswetlow** [comment]
Hey guys, 
Can't reproduce it on my Ubuntu on Windows10 + Node 9 so far.
How does the Service Request JSON (in the Alexa console) and the response look like?

You could also try the bst-proxy
jovo run --bst-proxy
(Don't forget to change the url in the Alexa Skill configuration)

@rv-ekramer  thanks for the support :)

**Comment by rv-ekramer** [comment]
No problem!

On Feb 24, 2018, at 6:44 AM, Alex <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey guys,
Can't reproduce it on my Ubuntu on Windows10 + Node 9 so far.
How does the Service Request JSON (in the Alexa console) and the response look like?

You could also try the bst-proxy
jovo run --bst-proxy
(Don't forget to change the url in the Alexa Skill configuration)

@rv-ekramer<https://github.com/rv-ekramer> thanks for the support :)

**Comment by photonfighter** [comment]
Hey guys, sorry about the late response. I tried the bst proxy, but that didn't work either. I did a clean ubuntu install in virtualbox and now everything works fine (no surprises there). I'm just pretty sure that my UOW installation is goofy. In the future, I will try again with UOW, but for now I'm kind of done with it. Thank you for all your help!

**Comment by photonfighter** [comment]
UPDATE: I believe that there was something funky because I still had the legacy UNIX subsystem installed on Windows, along with a funky installation of Ubuntu. After uninstalling everything and doing a clean install of Ubuntu on Windows, everything works fine. *grumbles at simplicity of solution*

**Comment by rv-ekramer** [comment]
I’m glad its working for you now. Lol, I feel like 90% of the super difficult problems have simple solutions like this.

[ignature_302724300]

Ethan Kramer
Front End Developer
1101 Red Ventures Drive
Fort Mill, SC  29707
