### ISSUE TITLE
app.json fails to interpolate from environment variable 

### ISSUE THREAD

**Issue by Jefftopia** [jovotech/jovo-cli#70]
## I'm submitting a...
- [x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
// `.env`
```
ARN_DEV=Foo
WEBHOOK_DEV=Bar
```
// `app.json`
```
"stages": {
    "dev": {
      "alexaSkill": {
        "endpoint": "${process.env.ARN_DEV}"
      },
    "googleAction": {
        "endpoint": "${pricess.env.WEBHOOK_DEV}"
    }
...
```

When running `jovo deploy`, app.json should receive, or the Jovo CLI should run app.json using above environment variables, replacing `${<key>}` with environment value.

- `alexaSkill.endpoint` should be Foo
- `googleAction.endpoint` should be Bar

## Current Behavior

1. `${process.env.ARN_DEV}` is _not_ being interpolated.
2. `${process.env.WEBHOOK_DEV}` is _not_ being interpolated.
3. When hard-coding `googleAction.endpoint`, the value is not being retrieved. 

### Error log
No error messages.

## Your Environment

* Jovo CLI version used: 1.2.6
* Operating System: OSX HighSierra 10.13.6

**Comment by janober** [comment]
Hello!
That will now work automatically with v2 of the framework. The data from the "app.json" like for example the "endpoint" does now get set in a JavaScript file the "project.js". So if you use:
```
`${process.env.ARN_DEV}`
```
it will interpolate it automatically.
