### ISSUE TITLE
jovo deploy to lambda fails when connected via a corporate proxy

### ISSUE THREAD

**Issue by niklasgoethe** [jovotech/jovo-cli#72]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
$>jovo deploy --target lambda

   √ Deploying Alexa Skill
     √ Uploading to lambda
       Deployed to lambda function: arn:aws:lambda:...function:helloworld

  Deployment completed.

## Current Behavior
$>jovo deploy --target lambda

   > Deploying Alexa Skill
     × Uploading to lambda
       -> connect ECONNREFUSED 63.32.73.187:443

connect ECONNREFUSED 63.32.73.187:443

## Your Environment
Connection to Internet via a corporate proxy.
Environment  variables http_proxy, https_proxy configured. 

* Jovo CLI version used: 1.2.11
* Operating System: windows 7, ..

=>jovo-cli/alexaUtils.js uses aws-sdk method lambda UpdateFunctionCode. 
aws-sdk guide: https://docs.aws.amazon.com/en_us/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html

alexaUtils.js:
//my fix to solve the problem: 
const proxy = require('proxy-agent');
var proxyServer = process.env.http_proxy ||
                  process.env.HTTP_PROXY ||
                  process.env.https_proxy ||
                  process.env.HTTPS_PROXY;
if (proxyServer) {
    AWS.config.update({
        httpOptions: {
            agent: proxy(proxyServer)
        }
    });
}

**Comment by jankoenig** [comment]
This should be solved now! Thanks @niklasgoethe. Let us know if you run into additional problems
