### ISSUE TITLE
jovo with my own server

### ISSUE THREAD

**Issue by mark-hahn** [jovotech/jovo-cli#8]
I have an existing app in node with httpserver and I want to use jovo.  Can I call jovo as a plug-in or does it have to run on its own server?

**Comment by photonfighter** [comment]
Without modification, I *believe* that you can't use your own server with jovo. However, I'm not sure I'd see the benefit of that. What advantage are you seeking from using your own server? (Anything is better than screwing with Lambda, so there's that)

**Comment by mark-hahn** [comment]
>  What advantage are you seeking from using your own server?

I have local services available that aren't on Lamba.  I don't know about
anything about Lambda but I assume Lambda could call my server, but why
have a middleman?

**Comment by aswetlow** [comment]
Is it an express server or a "plain" nodejs http server?
Replace that part in your index.js of your jovo project.
```javascript
if (app.isWebhook()) {
    const port = process.env.PORT || 3000;
    Webhook.listen(port, () => {
        console.log(`Example server listening on port ${port}!`);
    });
    Webhook.post('/webhook', (req, res) => {
        app.handleWebhook(req, res);
    });
}

exports.handler = (event, context, callback) => {
    app.handleLambda(event, context, callback);
};
```

To
Express:
```javascript
const express = require('express');
const server = express();
const bodyParser = require('body-parser');
server.use(bodyParser.json());

server.post('/', function (req, res) {
        app.handleWebhook(req, res);
});

server.listen(3000, function () {
    console.log('Example app listening on port 3000!');
});
```

httpServer:
```javascript
const http = require('http');
const bodyParser = require('body-parser');
const jsonParser = bodyParser.json();
http.createServer(function(req, res) {
    res.json = function(data) {
        this.write(JSON.stringify(data));
        this.end();
    };
    jsonParser(req, res, (error) => {
        app.handleWebhook(req, res);
    });
}).listen(3000);
```
Be aware that your HTTP requests need to be verified (if you want to publish your skill)
See https://github.com/mreinstein/alexa-verifier

**Comment by mark-hahn** [comment]
That is exactly what I wanted, thanks ...
