### ISSUE TITLE
Display full ASK/AWS error messages on deploy

### ISSUE THREAD

**Issue by internetofvoice** [jovotech/jovo-cli#81]
## I'm submitting a...
- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
If an ASK or AWS error occurs on `jovo deploy`, error message should be displayed in full. 

## Current Behavior
For enforcing an error message, I added a lambda version string (:$LATEST) to the endpoint configuration in project.js (using an AWS lambda function as an endpoint).  On deploy, this error message is shown on command line:
```
 ✔ Bundle Project
    (...)
    ❯ Deploying Alexa Skill
      ✖ Updating Alexa Skill project for ASK profile default
        -> Invalid Lambda ARN arn:aws:lambda:region:123:function:testFunction:$LATEST for EU region. Please provid…
        (...)
```
The error message ("Invalid Lambda ARN (...) Please provid...") is truncated here. In this case, I can guess the problem, but sometimes it would be cool to have the full error message to figure out, what was wrong.  

### Error log
(No error). 

## Your Environment
* Jovo CLI version used: 2.0.14
* Operating System: Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

TIA & best regards,
Alex.

**Comment by jankoenig** [comment]
Thank you! Added to the list

**Comment by janober** [comment]
That issue got fixed a while ago. So close now.
If it does not work like expected please comment here again.
