### ISSUE TITLE
Add additional default values to skill.json

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-cli#87]
## I'm submitting a...

- [ ] Bug report
- [X] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
In order to create a beta test for an Alexa skill, certain fields need to be included in skill.json. Add required fields with default values.

## Current Behavior
When the skill.json file is created, it is missing needed values.

### Error log
None

## Your Environment
* Jovo CLI version used: 2.2.5
* Operating System: Windows 10 Pro

**Comment by rubenaeg** [comment]
Closing this as a pull request addressing this issue has already been merged.
