### ISSUE TITLE
Deploy lamda to multiple aws regions at same time

### ISSUE THREAD

**Issue by ihr-it-projekt** [jovotech/jovo-cli#89]
## I'm submitting a...

- [ ] Bug report
- [x ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
hi, i have multiple lamda functions (same code) for several regions (one per region). It is possible to delpoy all lamda functions with jovo deploy at same time?

**Comment by rubenaeg** [comment]
I don't think this is supported by default, however you could try to add different endpoints for different [stages](https://www.jovo.tech/docs/staging) and create an npm script for automatically deploying to all your endpoints. 

Closing this for now, if the issue still persists, feel free to reopen.
