### ISSUE TITLE
Platform-specific intents incorrect on build

### ISSUE THREAD

**Issue by sdaoud** [jovotech/jovo-cli#95]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Running latest Jovo V2, in my language model file, I have this:

```
"intents": [
  {
    "name": "CatchAllIntent",
    "phrases": [
      "{query}"
    ],
    "inputs": [
      {
        "name": "query",
        "type": {
          "dialogflow": "@sys.any",
          "alexa": "CatchAll"
        }
      }
    ]
  }
]
```

Running `jovo build` should create a `CatchAllIntent` intent for both Alexa and DialogFlow. Dialogflow should use system entity `@sys.any` whereas Alexa should use the custom `CatchAll` entity (not shown here).

## Current Behavior
If I run `jovo build` the dialogflow `platforms` folder shows the `CatchAllIntent` using the `CatchAll` entity, rather than `@sys.any`.

If I run `jovo build --platform googleAction` the `CatchAllIntent` for dialogflow uses `@sys.any` as expected.

## Your Environment

* Jovo CLI version used: 2.2.8
* Operating System: OSX 10.14.5

**Comment by aswetlow** [comment]
Thanks! I can reproduce it. 

Fixed it and will publish it soon. 

Workaround for now: Run `jovo build` for each platform separately.

```shell
> jovo build --platform alexaSkill
```

```shell
> jovo build --platform googleAction
```
